### ISSUE TITLE
Need help with the below error when I update the script that contains the default example

### ISSUE THREAD

**Issue by Capitaplc** [IBM/pySigma-backend-QRadar-AQL#1]
![image](https://github.com/IBM/pySigma-backend-QRadar-AQL/assets/108936672/4a26b650-4daf-49dc-8844-0a3820aebf5a)

**Comment by noaakl** [comment]
Hey, there's a problem with the indentation. 'condition' should be indented the same as 'selection', but there is extra space before 'condition'.

**Comment by Capitaplc** [comment]
> Hey, there's a problem with the indentation. 'condition' should be indented the same as 'selection', but there is extra space before 'condition'.

Thank you! Silly me :)
